### ISSUE TITLE
gaft遗传算法交流

### ISSUE THREAD

**Issue by abcgreat11** [ASTARCHEN/ART2py#1]
您好！
偶然地我看到您了解过gaft。但是因为不方便在那边的issue里面与您交流，也没找到您的联系邮箱，所以特意在此和您交流一下，如果打搅了请给予批评和指正，谢谢您啦！
我在此真心地建议您使用更加权威的Python遗传和进化算法框架。gaft功能相当的单一，执行效率相当很低，而且没有权威性，对于复杂约束优化问题、多目标优化问题等无能为力。
我是之前从gaft弃坑的一名用户，之前在他的github上发言吐槽直接被他删了。现在真的是非常建议您不要浪费时间去学习和使用gaft框架了，真的会吃亏的。
真心地建议您使用更加权威、易学的国内高校开源的Python遗传和进化算法框架。
打搅您了，谢谢您啦！

**Comment by ASTARCHEN** [comment]
你好。对于你提到的问题，我做一下解释。
首先说一下我比较赞同的地方
1. gaft功能相当的单一。这点我比较赞同。GAFT确实是一个功能单一（只支持遗传算法）的框架。
2. 对于复杂约束优化问题、多目标优化问题等无能为力。这点无法否认，确实是的。
有待讨论的地方有一下几点
1. 执行效率低。对于执行效率，通读源码，GAFT是基于原生的python。python语言的局限于此，效率确实是硬伤。不过，既然用到python，本身对执行时间的要求不会很高。（如果实在要提高效率，一般会用到C或者FORTRAN）
2. 对于没有权威性。目前GA我认为虽然已经很成熟，但是代码是实现算法思路的工具，也并没有权威一说。
在使用的过程中，我这边对ta的评价
1. 从代码角度，作者思路清晰，使用了一些装饰器来构建项目，在一些细节处理上也做的比较出色。从源码的角度上来看，确实有值得学习的地方。
2. ta的代码协议基于GPL，对于我商用有局限。
3. 如你所言，复杂约束优化问题、多目标优化问题等无能为力。

我在后来实现的一些算法（只支持连续型单目标的优化）
https://gitee.com/hoops/snowland-algorithm-python/tree/master/slapy/swarm
里面暂时不支持GA，之前想加GAFT进去，后来发现许可证的GPL，所以加上后删除了。
如果有兴趣的话，可以帮忙补充GA算法，将不胜感谢。
在这里留个邮箱astar@snowland.ltd。欢迎交流。
